### PR TITLE
add the rust plugin example code

### PR DESCRIPTION
**Pull request by NMFR**

### CODE REVIEW

**Comment by asantos00** [comment]
Am I able to run it already?

**Comment by NMFR** [comment]
> Am I able to run it already?

Yes. `make run` for docker and 'make local-run' for local (requires rust and deno installed). As of now only tested on Ubuntu.

This is just the test code in deno repo, did not had time yet to start changing code, was just focusing on getting it to run.

**Comment by asantos00** [comment]
Cool, this way I can try it out on the Deno side too 🎉

**Comment by NMFR** [comment]
Think this is ready to get merged. Code part is done we should focus on the article now.

**Pull request merged**
